package com.example.calculator.engine

sealed class Token {
    data class Number(val value: java.math.BigDecimal) : Token()
    object Plus : Token()
    object Minus : Token()
    object Multiply : Token()
    object Divide : Token()
    object Power : Token()
    object Percent : Token()
    object Factorial : Token()
    object LParen : Token()
    object RParen : Token()
    object Negate : Token()
    object Pi : Token()
    object E : Token()
    object Sin : Token()
    object Cos : Token()
    object Tan : Token()
    object Asin : Token()
    object Acos : Token()
    object Atan : Token()
    object Log : Token()
    object Ln : Token()
    object Sqrt : Token()
    object Cbrt : Token()
    object Square : Token()
    object Cube : Token()
    object End : Token()
}
